// You are given an array of integers a. A new array b is generated by
// rearranging the elements of a in the following way:

// b[0] is equal to a[0];
// b[1] is equal to the last element of a;
// b[2] is equal to a[1];
// b[3] is equal to the second-last element of a;
// and so on.
// Your task is to determine whether the new array b is sorted in strictly ascending order or not

function mergeStrings(s1, s2) {
  let newS1 = s1.split("");
  let newS2 = s2.split("");
  const countS1 = {};
  const countS2 = {};
  let newWord = "";

  for (let char of s1) {
    if (countS1[char]) {
      countS1[char]++;
    } else {
      countS1[char] = 1;
    }
  }
  for (let char of s2) {
    if (countS2[char]) {
      countS2[char]++;
    } else {
      countS2[char] = 1;
    }
  }

  while (newS1.length !== 0 || newS2.length !== 0) {
    if (newS1.length === 0) {
      newWord += newS2.shift();
    } else if (newS2.length === 0) {
      newWord += newS1.shift();
    } else if (countS1[newS1[0]] === countS2[newS2[0]]) {
      if (newS1[0] > newS2[0]) {
        newWord += newS2.shift();
      } else {
        newWord += newS1.shift();
      }
    } else if (countS1[newS1[0]] > countS2[newS2[0]]) {
      newWord += newS2.shift();
    } else if (countS1[newS1[0]] < countS2[newS2[0]]) {
      newWord += newS1.shift();
    }
  }
  return newWord;
}

console.log(mergeStrings("super", "tower"));
console.log(mergeStrings("aabb", "abab"));
console.log(mergeStrings("apple", "pie"));

function alternatingSort(a) {
  const b = [];
  count = 0;

  while (a.length !== 0) {
    if (count % 2 === 0) {
      b.push(a.shift());
      count++;
    } else {
      b.push(a.pop());
      count--;
    }
  }

  let anotherB = b.slice();
  console.log(b);
  console.log(JSON.stringify(anotherB.sort((a, b) => a - b)));
  if (JSON.stringify(anotherB.sort((a, b) => a - b)) === JSON.stringify(b)) {
    return true;
  } else {
    return false;
  }
}

console.log(alternatingSort([1, 3, 5, 6, 4, 2]));
console.log(alternatingSort([1, 2, 5, 6, 4, 3]));
